export const ERROR_CODES = {
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	EMAIL_EXISTS: "EMAIL_EXISTS",
	ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
	ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
	ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
	TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	SERVER_ERROR: "SERVER_ERROR",
} as const;
